# Powered by Application Builder: https://github.com/golift/application-builder
jobs:
  include:
  - os: osx
    osx_image: xcode12
    language: go
    go: 1.16.x
  - os: linux
    dist: bionic
    services: docker
    language: go
    go: 1.16.x
git:
  depth: false
addons:
  homebrew:
    packages:
    #- rpm
    #- gnu-tar
    - upx
  apt:
    packages:
    - ruby-dev
    - rpm
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
    - zip
    - debsigs
    - gnupg
    - expect
    - upx
install:
  - mkdir -p $(go env GOPATH)/bin
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm install 2.6.0; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm 2.6.0 do gem install --no-document fpm; fi
before_script:
  # Create your own deploy key, tar it, and encrypt the file to make this work. Optionally add a bitly_token file to the archive.
  - openssl aes-256-cbc -K $encrypted_772fc4772f04_key -iv $encrypted_772fc4772f04_iv -in .secret_files.tar.enc -out .secret_files.tar -d
  - tar -xf .secret_files.tar
  - gpg --import gpg.signing.key
  - rm -f gpg.signing.key .secret_files.tar
  - source settings.sh
script:
  # Test Go and Docker.
  - make test
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make docker; fi
  # Test built docker image.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker run $BINARY -v 2>&1 | grep -Eq "^$BINARY, version $VERSION"; fi
  # Build everything
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then rvm 2.6.0 do make release; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then make dmg; fi
after_success:
  # Display Release Folder
  - ls -l release/
  # Setup the ssh client so we can clone and push to the homebrew formula repo.
  # You must put github_deploy_file into .secret_files.tar.enc
  # This is an ssh key added to your homebrew forumla repo.
  - |
    mkdir -p $HOME/.ssh
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> $HOME/.ssh/config
    [ ! -f github_deploy_key ] || (mv github_deploy_key $SSH_FILE \
      && chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
        "Host github.com" \
        "  IdentityFile $SSH_FILE" \
        "  StrictHostKeyChecking no" \
        "  LogLevel ERROR" >> $HOME/.ssh/config)
deploy:
  - provider: packagecloud
    repository: "pkgs"
    username: "golift"
    token:
      secure: "KlMzZdcu46vS5emuS+uAYjwCstbE7rgXbfOyQDw70Qp2MuXDI4aPqt//TcIwcJZN0rjaqLX6hf5P7L0qV+ro676Br5gNm0YZWNN3W165QGTH5LwBEt6cFxOD/hKVKSE7wx7XXd++/Di2Gy1f7Gi0EIpit0rBpDy9u9GHwIkgU57k/ET5kcIAfsc4EHnF2oQEPjk0qunrdmkM29unbKExOa7M5vcJK1hUggLPRszJR6bIaPsT1wJfaw/+oS59y4D8f/LvPjDD6oirEdwEGLqC6slZ2GIWLAGB747UIeXcRTUym4xpUtcr4M/kQ9ZWR98MifBCkcnUgRnXiwPxhWw5QKUEAc41fQY/HIyZyqokdY7z3mALcPdfGn9KoBZw1JOgxKMPCO9jU+sf3ZyC0G0Ue6oS3BPNN0FKAMAF7aWzpFl01ou8a+q7vJq/OBrTOLYrcWW+yWGHtiS95dTJLMFaqZ1jaHrwk6jz5bRvcSHuCXhoXQZsMoOLF3gZWt6Mv6GGqSxPShDVWXZ0n8OSZOtp2W1e1QPG7hRnat+Ga5aDZrWtqvcf3LmN0hMijXk2EStSShBNjpcCezMfn9i4m83B82aD6ZB/0J+rBLs8qVqtEc2LGavPPKu5AlsxD3ffvzQ3342RBrFEZDuVV+GMSGt51v02KcT3UMU70sgT+VP1BTw="
    dist: "ubuntu/focal"
    local-dir: release
    package_glob: "*.deb"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: packagecloud
    repository: "pkgs"
    username: "golift"
    token:
      secure: "KlMzZdcu46vS5emuS+uAYjwCstbE7rgXbfOyQDw70Qp2MuXDI4aPqt//TcIwcJZN0rjaqLX6hf5P7L0qV+ro676Br5gNm0YZWNN3W165QGTH5LwBEt6cFxOD/hKVKSE7wx7XXd++/Di2Gy1f7Gi0EIpit0rBpDy9u9GHwIkgU57k/ET5kcIAfsc4EHnF2oQEPjk0qunrdmkM29unbKExOa7M5vcJK1hUggLPRszJR6bIaPsT1wJfaw/+oS59y4D8f/LvPjDD6oirEdwEGLqC6slZ2GIWLAGB747UIeXcRTUym4xpUtcr4M/kQ9ZWR98MifBCkcnUgRnXiwPxhWw5QKUEAc41fQY/HIyZyqokdY7z3mALcPdfGn9KoBZw1JOgxKMPCO9jU+sf3ZyC0G0Ue6oS3BPNN0FKAMAF7aWzpFl01ou8a+q7vJq/OBrTOLYrcWW+yWGHtiS95dTJLMFaqZ1jaHrwk6jz5bRvcSHuCXhoXQZsMoOLF3gZWt6Mv6GGqSxPShDVWXZ0n8OSZOtp2W1e1QPG7hRnat+Ga5aDZrWtqvcf3LmN0hMijXk2EStSShBNjpcCezMfn9i4m83B82aD6ZB/0J+rBLs8qVqtEc2LGavPPKu5AlsxD3ffvzQ3342RBrFEZDuVV+GMSGt51v02KcT3UMU70sgT+VP1BTw="
    dist: "el/6"
    local-dir: release
    package_glob: "*.rpm"
    skip_cleanup: true
    cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
  - provider: releases
    token:
      # to get a secure api key, run: travis setup releases
      # make a copy of this file first because that command will change it.
      # or: make a new key manually at https://github.com/settings/tokens/new
      # then: echo <NEW_KEY_FROM_GH> | travis encrypt
      secure: "CEeczHbmPCs54puNInkE7pCwPrR13Rl054PVtfElsXGD62DoJB6DAW2M9XEEVQPAaCZHj8K1mTRKA6h0W1xSyT0YYZkcVRzrpqkntGo1swfRtPj3nnUCJEqvABrMJWv7c/145LmcoXpalxMCHVOioQJO87hZf+iV+Keb2HwIUTChglVpjcDtTeSrQlKSn58jiYSaVQs4cgdrXhlBFxTwgeyVBTbbg7nU036GgCnQoU9gzWZysa6XGuO4MyoehRfNj5RHIbPITWqmUSbxUHV4G25+SrcP2MBEdZawvWKSrnSvKdYuczhmhv9rVIxNNOM+jRqIpLlaJjY+o1kWL9OBT/e9eqyfpvG7b1sYWyuzQPPNH02hV5NyXLobXtWDpuL8gCbtF/dLTjsom2PGC/g0/aeJ0GvwmSA/c2P8Oc2AajHX9kJ9JSq1R7Kg0JKHFZRwsdUb1sfoc2oyO9sh7YpMDx/6eVnkTekbhpXLdJyJd4pWj6FLllZP6GMVQehyOUANADKZQ1yWH+gPUbgvieEjd54ZqZO5/yPzOI0eIw9j48BCMRgjkY5wZkUJ+lLjN5qMS5Zrc4rSI4kU0UKrvvr9O32EczV6f54lRxp9TK89NuPkkcbCAWa9iVasdONOho5TRKRirp3W3jqWm2rSbKWjPg9axJ2ts53I8w8ybMdyFRE="
    overwrite: true
    skip_cleanup: true
    cleanup: false
    file_glob: true
    file: release/*
    on:
      tags: true
  - provider: script
    script: bash scripts/formula-deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
